### ISSUE TITLE
beállítások figma

### ISSUE THREAD

**Issue by tbrjedlik** [tbrjedlik/szinozon#2]

**Comment by VargaDaniel2007** [comment]
Figma Prototype link:
https://www.figma.com/proto/CtdC57tocfJWaMFHjuzkGA/Sz%C3%ADn%C3%B6z%C3%B6n-terv?node-id=2-2&t=D0lajMgA33elPjHv-1
Figma Design link: 
https://www.figma.com/design/CtdC57tocfJWaMFHjuzkGA/Színözön-terv?node-id=2-2&node-type=canvas&t=D0lajMgA33elPjHv-0
(itt tudtok kérni edit permissiont)
